apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: supervisor-agent
  labels:
    app: supervisor-agent
spec:
  template:
    metadata:
      labels:
        app: supervisor-agent
    agents:
      - IntentClassifier
    prompt: I want to fetch the current stock prices for Apple and Microsoft, and then analyze which one has performed better over the past week.
    steps:
      - name: classify_intent
        agent: IntentClassifier